### ISSUE TITLE
The library 'package:parallax_bg/parallax_bg.dart' is legacy, and should not be imported into a null safe library.

### ISSUE THREAD

**Issue by jonnyplow** [kumar-aakash86/parallax_bg#1]
SETUP:
sdk: ">=2.12.0 <3.0.0"
parallax_bg: ^1.0.4

ISSUES: I receive errors - 

"The library 'package:parallax_bg/parallax_bg.dart' is legacy, and should not be imported into a null safe library."

"Error: Cannot run with sound null safety, because the following dependencies don't support null safety:"

Can you make this for null safety?

**Comment by kumar-aakash86** [comment]
Hi @jonnyplow 
I wanted to create this null-safe but the sensor libraries are not null-safe at the time I was creating this plugin. 
Let me check if those libraries are updated yet or not. If they are updated then I can convert this to null safe.

Give me 1-2 days.

**Comment by jonnyplow** [comment]
Oh wow that would be awesome! Thanks.

**Comment by jonnyplow** [comment]
Hi Kumar. Any luck making this null safe?

**Comment by kumar-aakash86** [comment]
@jonnyplow 
Thanks for reminding me. I totally forgot to update the library.
I have already made the changes & it will be up in few hours.

**Comment by kumar-aakash86** [comment]
@jonnyplow 
Null safety version is updated on pub. It will take few hours to officially verifying the package so it will be available soon.
Please test it & raise an issue if you face any problem.

Thanks

**Comment by jonnyplow** [comment]
Thanks Kumar!! working now!
